### ISSUE TITLE
Lean's curated library collection

### ISSUE THREAD

**Issue by cipher1024** [NeilStrickland/lean_lib#1]
Hello fellow Leaner! I'm preparing a collection of Lean libraries to make it as painless as possible to import each other's libraries. I'd like to include `lean_lib` into that collection but I haven't been able to make it compile with the latest version of mathlib. 

Would you be interested making `lean_lib` a part of that collection? At the moment, I'm simply setting up a monthly snapshot where I tag a commit of each library as `snapshot-2019-10` and having a build system making sure that all the selected versions of all the libraries work together well. This way, when someone imports multiple libraries, we simply have to select one snapshot of the Lean ecosystem and know that our dependencies will make sense.

Cheers,
Simon

**Comment by NeilStrickland** [comment]
Closing as stale
